---
- hosts: targets
    
  tasks:
  - name: Set SELinux on permissive mode
    selinux:
      policy: targeted
      state: permissive

  - name: Update system
    yum:
      name: '*'
      state: latest

  - name: Install EPEL
    yum:
      name: "epel-release"
      state: latest

  - name: Print REPOS
    command: yum repolist
    args:
        warn: false
    register: repos

  - debug: msg="{{ repos.stdout }}"

  - name: Install APACHE web server
    yum: name=httpd
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Uninstall APACHE web server
    yum:
      name: "{{ item }}"
      state: absent
    loop:
      - httpd
      - httpd-tools
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Install NGINX web server
    package: 
      name: "{{ web_server }}"
      state: latest